[application]
app-01.plab.internal ansible_host=10.208.12.103

[monitoring]
metrics-01.plab.internal ansible_host=10.208.12.102

[management]
localhost ansible_connection=local

[ipaserver]
ipa-01.plab.internal ansible_host=10.208.12.105

[desktop]
showcase-01.plab.internal ansible_host=10.208.12.104

[ipaserver:vars]
ipaadmin_password={{ vault_ipaadmin_password }}
ipadm_password={{ vault_ipadm_password }}
ipaserver_domain=plab.internal
ipaserver_realm=PLAB.INTERNAL

[ipaclients]
metrics-01.plab.internal ansible_host=10.208.12.102
app-01.plab.internal ansible_host=10.208.12.103
localhost ansible_connection=local
showcase-01.plab.internal ansible_host=10.208.12.104

[ipaclients:vars]
ipaadmin_password={{ vault_ipaadmin_password }}
ipadm_password={{ vault_ipadm_password }}
ipa_server=ipa-01.plab.internal
ipaserver_domain=plab.internal
ipaserver_realm=PLAB.INTERNAL
ipaclient_force_join=yes
ipaclient_mkhomedir=yes

[mailserver]
showcase-01.plab.internal ansible_host=10.208.12.104

[mailclient]
metrics-01.plab.internal ansible_host=10.208.12.102
app-01.plab.internal ansible_host=10.208.12.103
localhost ansible_connection=local
ipa-01.plab.internal ansible_host=10.208.12.105
