apiVersion: 1
contactPoints:
  - orgId: 1
    name: ntfy
    receivers:
      - uid: ntfy-webhook
        type: webhook
        settings:
          url: http://10.208.12.102:9093/alerts
          httpMethod: POST

policies:
  - orgId: 1
    receiver: ntfy
    group_by: [severity]
    routes:
      - receiver: ntfy
        matchers:
          - severity = critical
        group_wait: 0s
      - receiver: ntfy
        matchers:
          - severity = warning
        group_wait: 30s
